-- MySQL Script generated by MySQL Workbench
-- Thu Dec 22 22:10:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`exchanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exchanges` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`symbols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`symbols` (
  `id` INT NOT NULL,
  `ticker` VARCHAR(45) NOT NULL DEFAULT 'exchange:symbol',
  `name` VARCHAR(45) NOT NULL,
  `lastSync` DATETIME NOT NULL,
  `exchange_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_symbol_Exchanges1_idx` (`exchange_id` ASC) VISIBLE,
  UNIQUE INDEX `exchange_ticker_UNIQUE` (`exchange_id` ASC, `ticker` ASC) INVISIBLE,
  CONSTRAINT `fk_symbol_Exchanges1`
    FOREIGN KEY (`exchange_id`)
    REFERENCES `mydb`.`exchanges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marketHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marketHistory` (
  `id` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  `symbol_id` INT NOT NULL,
  `open` DOUBLE NOT NULL,
  `high` DOUBLE NOT NULL,
  `low` DOUBLE NOT NULL,
  `close` DOUBLE NOT NULL,
  `volume` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marketHistory_symbol_idx` (`symbol_id` ASC) VISIBLE,
  UNIQUE INDEX `symbol_timestamp_UNIQUE` (`symbol_id` ASC, `timestamp` ASC) VISIBLE,
  CONSTRAINT `fk_marketHistory_symbol`
    FOREIGN KEY (`symbol_id`)
    REFERENCES `mydb`.`symbols` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
